import mongoose, { Document, Schema, Types } from 'mongoose';

export interface ILuckyChest {
    upgradeFeeGold: number;
    nextUpgradeFeeGold: number;

    minGold: number;
    maxGold: number;
    dragonChestChance: number;

    idleMaxTimeMinute: number;
    idleMinGold: number;
    idleMaxGold: number;
    idleMinChest: number;
    idleMaxChest: number;
}
export interface IDragonChest {
    dragonBallChances: [number, number, number, number, number, number, number];
}

export interface IDragonBall {
    diamondReward: number;
}

export interface ICfgItem extends Document {
    _id: Types.ObjectId;
    type: 'lucky_chest' | 'dragon_chest' | 'dragon_ball';
    level: number;
    name: string;
    description: string;
    imageSlug: string;
    // for lucky_chest & dragon_chest, this `properties` will be rewritten by levels dynamiccally
    properties: ILuckyChest | IDragonChest | IDragonBall;
}

const cfgItemSchema: Schema = new Schema({
    type: { type: String, required: true, enum: ['lucky_chest', 'dragon_chest', 'dragon_ball'] },
    level: { type: Number, default: 1 },
    name: { type: String, required: true },
    description: { type: String, required: true },
    imageSlug: { type: String },
    properties: { type: Object }, // this field is generated by code, doesn't have data in db
}, { timestamps: true });

export default mongoose.model<ICfgItem>('CfgItem', cfgItemSchema);
